#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=['src/squirrel-3.2/include'])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

sqstdlib_sources = [
#    "src/squirrel-3.2/sqstdlib/sqstd_aux.cpp",
    "src/squirrel-3.2/sqstdlib/sqstd_math.cpp",
    "src/squirrel-3.2/sqstdlib/sqstd_string.cpp",
    "src/squirrel-3.2/sqstdlib/sqstd_system.cpp",
    "src/squirrel-3.2/sqstdlib/sqstd_io.cpp",
    "src/squirrel-3.2/sqstdlib/sqstd_blob.cpp",
]



# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")
sources += Glob("src/squirrel-3.2/squirrel/*.cpp")
sources += Glob("src/squirrel-3.2/sqstdlib/*.cpp")



if env["platform"] == "macos":
    library = env.SharedLibrary(
        "demo/bin/libgodotsquirrel.{}.{}.framework/libgdexample.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
elif env["platform"] == "ios":
    if env["ios_simulator"]:
        library = env.StaticLibrary(
            "demo/bin/libgodotsquirrel.{}.{}.simulator.a".format(env["platform"], env["target"]),
            source=sources,
        )
if env["platform"] == "windows":
    library = env.SharedLibrary(
        "demo/bin/libgodotsquirrel.{}.{}.dll".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "demo/bin/libgodotsquirrel.{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
